import 'package:flutter/foundation.dart';

/// Proste tłumaczenia PL/EN dla generatora.
class LangProvider extends ChangeNotifier {
  String _lang = 'pl';
  String get lang => _lang;

  void toggle() {
    _lang = _lang == 'pl' ? 'en' : 'pl';
    notifyListeners();
  }

  String t(String key) => _strings[_lang]?[key] ?? _strings['pl']?[key] ?? key;

  static const Map<String, Map<String, String>> _strings = {
    'pl': {
      'step1_title': 'BRANDING',
      'step1_sub': 'Nazwa i wygląd launchera',
      'step2_title': 'SERWER',
      'step2_sub': 'Dane serwera Valheim',
      'step3_title': 'PANEL',
      'step3_sub': 'Adres panelu serwera',
      'step4_title': 'BEZPIECZEŃSTWO',
      'step4_sub': 'Szyfrowanie konfiguracji',
      'step_of': 'KROK {n} Z 4',
      'back': 'WSTECZ',
      'next': 'DALEJ',
      'generate': 'GENERUJ LAUNCHER',
      'server_name': 'Nazwa serwera',
      'server_name_hint': 'np. Moja Baza',
      'output_label': 'Plik wyjściowy: "{name} Launcher.exe"',
      'no_name': 'Wprowadź nazwę serwera',
      'background': 'Tło launchera (PNG / MP4)',
      'no_file': 'Nie wybrano pliku',
      'browse': 'Przeglądaj',
      'server_addr': 'Adres serwera Valheim',
      'server_addr_hint': '192.168.1.100:2456',
      'server_pass': 'Hasło do serwera',
      'optional': 'opcjonalne',
      'copy': 'Kopiuj',
      'ftp_host': 'Host FTP/SFTP',
      'ftp_host_hint': 'np. cybrancee.game.com',
      'ftp_port': 'Port',
      'ftp_user': 'Użytkownik',
      'ftp_user_hint': 'login',
      'ftp_pass': 'Hasło FTP',
      'ftp_pass_hint': 'hasło',
      'panel_url': 'Adres panelu (HTTPS)',
      'panel_url_hint': 'np. https://valheim.klans.eu',
      'engine_repo': 'Repozytorium silnika (GitHub)',
      'engine_repo_hint': 'właściciel/repo — puste = domyślne',
      'engine_repo_note': 'Stąd launcher i updater pobierają aktualizacje silnika. Zostaw puste, jeśli nie masz własnego forka.',
      'test_conn': 'Testuj połączenie',
      'testing': 'Testowanie...',
      'salt_intro': '🔐 Salt szyfruje wszystkie hasła w wygenerowanych plikach.\nBez salt nikt nie może uruchomić/zaktualizować launchera.',
      'salt_hint': 'min. 30 znaków',
      'generate_salt': 'Generuj',
      'salt_warn_title': 'Ważne — Nie zgub Salt!',
      'salt_chars': '{n} znaków',
      'salt_min_warn': 'Salt musi mieć min. 30 znaków ({n} brakuje)',
      'salt_box_title': 'Zguba Salt = reset konfiguracji',
      'salt_box_body': 'Salt jest przechowywany w rejestrze Windows. Jeśli go zgubisz, launcher, patcher i updater nie będą mogły się połączyć z FTP.',
      'salt_checkbox': 'Rozumiem — zapisz salt w rejestrze',
      'done_prefix': 'Gotowe: ',
      'error_prefix': 'Błąd: ',
      'generating': 'Generowanie...',
    },
    'en': {
      'step1_title': 'BRANDING',
      'step1_sub': 'Name and appearance of your launcher',
      'step2_title': 'SERVER',
      'step2_sub': 'Valheim server details',
      'step3_title': 'PANEL',
      'step3_sub': 'Server panel address',
      'step4_title': 'SECURITY',
      'step4_sub': 'Configuration encryption',
      'step_of': 'STEP {n} OF 4',
      'back': 'BACK',
      'next': 'NEXT',
      'generate': 'GENERATE LAUNCHER',
      'server_name': 'Server name',
      'server_name_hint': 'e.g. My Base',
      'output_label': 'Output: "{name} Launcher.exe"',
      'no_name': 'Enter server name',
      'background': 'Launcher background (PNG / MP4)',
      'no_file': 'No file selected',
      'browse': 'Browse',
      'server_addr': 'Valheim server address',
      'server_addr_hint': '192.168.1.100:2456',
      'server_pass': 'Server password',
      'optional': 'optional',
      'copy': 'Copy',
      'ftp_host': 'FTP/SFTP host',
      'ftp_host_hint': 'e.g. cybrancee.game.com',
      'ftp_port': 'Port',
      'ftp_user': 'Username',
      'ftp_user_hint': 'login',
      'ftp_pass': 'FTP password',
      'ftp_pass_hint': 'password',
      'panel_url': 'Panel address (HTTPS)',
      'panel_url_hint': 'e.g. https://valheim.klans.eu',
      'engine_repo': 'Engine repository (GitHub)',
      'engine_repo_hint': 'owner/repo — empty = default',
      'engine_repo_note': 'The launcher and updater pull engine updates from here. Leave empty unless you run your own fork.',
      'test_conn': 'Test connection',
      'testing': 'Testing...',
      'salt_intro': '🔐 Salt encrypts all passwords in generated files.\nWithout salt nobody can run or update the launcher.',
      'salt_hint': 'min. 30 characters',
      'generate_salt': 'Generate',
      'salt_warn_title': 'Important — Don\'t lose your Salt!',
      'salt_chars': '{n} chars',
      'salt_min_warn': 'Salt must be at least 30 chars ({n} missing)',
      'salt_box_title': 'Losing Salt = full reconfiguration',
      'salt_box_body': 'Salt is stored in Windows registry. If lost, launcher, patcher and updater won\'t be able to connect to FTP.',
      'salt_checkbox': 'I understand — save salt to registry',
      'done_prefix': 'Ready: ',
      'error_prefix': 'Error: ',
      'generating': 'Generating...',
    },
  };
}
